version: '3'
services:
  game_store:
    image: redis:6.0-rc-buster
    restart: always
  
  socketio_pubsub:
    image: redis:6.0-rc-buster
    restart: always

  game_server:
    image: senavi/presidents_game_server:latest
    ports:
      - "80:8000"
    restart: always
  
  game_god:
    image: senavi/presidents_game_god:latest
    restart: always
